# Generated by Django 5.2.5 on 2025-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_herois/'),
        ),
    ]
