# Generated by Django 5.2.5 on 2025-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_hero_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
